services:
    otel-lgtm:
        image: grafana/otel-lgtm:latest
        ports:
            - '${TELEMETRY_PORT}:3000' # Grafana UI
            - '4317:4317' # OTLP gRPC
            - '4318:4318' # OTLP HTTP
